### ISSUE TITLE
[CLI] Events header "PINCIPAL" misspelled

### ISSUE THREAD

**Issue by scottford-lw** [lacework/go-sdk#118]
One of the column headers in the events output is misspelled. It says "PINCIPAL" but should say "PRINCIPAL"

https://github.com/lacework/go-sdk/blob/621635884fb9fb34210e7d66964c1aca65b8e537/cli/cmd/event.go#L300

**Comment by afiunelw** [comment]
Closed by https://github.com/lacework/go-sdk/pull/119
