### ISSUE TITLE
bug: `lacework completion bash/fish/zsh` requires authentication

### ISSUE THREAD

**Issue by p-linnane** [lacework/go-sdk#1182]
**Describe the bug**
Shell completions cannot be generated until a valid account/key/secret are provided via `lacework configure`

**To Reproduce**
1. Install `lacework-cli`
2. Run `lacework completion bash`

**Expected behavior**
The bash completion is printed to stdout

**Please complete the following information):**
 - OS: macOS Ventura 13.2.1
 - Version v1.13.2

**Comment by afiune** [comment]
@p-linnane Thank you so much for highlighting this issue, let me go ahead and fix it now, since it is a pretty simple fix.

<img src="https://media0.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>
