### ISSUE TITLE
feat: Adding shell completion would be very nice.

### ISSUE THREAD

**Issue by pkruesi** [lacework/go-sdk#1591]
I like your cli lacework tool.
It could be much more easier to work with it it would have shell completion like many other cli tools.

**Comment by pkruesi** [comment]
Just found in the [doku](https://docs.lacework.net/cli/commands/lacework_completion) that completion is available.
Running the command with `lacework -h` shows in the help that `lacework completion` sub-command. But running only `lacework` does not show the `lacework completion` sub-command in the help. looks like a bug.

**Comment by afiune** [comment]
@pkruesi Thank you so much for opening this issue! 💯 - We are glad you like our CLI 🥇 

I'm glad you found the `lacework completion` command, and thank you for reporting that only running `lacework` without flags doesn't show that command, we can go fix that with this issue.

Further more, I'll ask our documentation team to put this upfront into our main CLI documentation at https://docs.lacework.net/cli

**Comment by sthetland** [comment]
Thanks for the feedback. I've added a section that introduces this feature to the introductory page on the CLI here: https://docs.lacework.net/cli#enable-command-autocomplete
