### ISSUE TITLE
feat: add generate sub-command to the cli for automation templates

### ISSUE THREAD

**Issue by scottford-lw** [lacework/go-sdk#202]
As a customer of Lacework I would like to be able to install the Lacework CLI and run a `lacework generate terraform` command that generates files for automating an environment. 

Example:
```
$ lacework generate terraform <cloud> <module_type> 
Generate Terraform templates for integrating cloud environments with Lacework.

--cloud aws, gcp, azure

--module_type config, cloudtrail
```

**Comment by declanwilson-lw** [comment]
I haven't really explore the cli, but can we generate the terraform, and run the terraform (download tf binary, spin out a process to do the terraform (commander), and create the integration ... all from 1 call.

Can we position the cli tool as the single source of entry-point to Lacework, creating inbound integrations (AWS, GCP, Azure) as well as all the outbound integrations (Jira, slack ... ) ?

**Comment by dmurray-lacework** [comment]
Closed as this work has been completed
