### ISSUE TITLE
Different exit codes for different results

### ISSUE THREAD

**Issue by scarolan** [lacework/go-sdk#211]
User asked if we could do something like this:

0 script ran fine, no vulnerabilities
1 script had errors
2 vulnerability scan failed
etc.

he said this would make it even easier to integrate within ci/cd envs

**Comment by scottford-lw** [comment]
@scarolan @afiune I think this is a great idea and something we should dig into. I am pretty sure we all know the standard Nagios style output code for monitoring checks...

```
0 - Service is OK.
1 - Service has a WARNING.
2 - Service is in a CRITICAL status.
3 - Service status is UNKNOWN.
```

When it comes to exit codes here I think we are going to need more coverage, or flexibility to configure exit codes. A quick example of some of the status might include what @scarolan documented but what about all of these statuses:

Critical Vulns no fix
Critical vulns with fixes

Thresholds:
High and above with fixes
High and above no fixes

i would like to talk this through with customers but I think we need to consider the possibility that each pipeline might need to have flexibility define what to do with results. For instance, if we are talking about the build pipeline for a service that is external facing service then it will likely have tighter policy than something not as critical. I don't have answers here, but I think we need to talk to our customers

**Comment by afiune** [comment]
Closed by https://github.com/lacework/go-sdk/pull/352
