### ISSUE TITLE
Ability to filter by machine tags for host vulnerability

### ISSUE THREAD

**Issue by scottford-lw** [lacework/go-sdk#238]
Customer would like the ability to filter based off of machine tag when running `lacework vulnerability host list-hosts <cve_id>` command. 

The api does return machine tags...

```json
{
    "host": {
      "hostname": "ip-172-31-9-170",
      "machine_id": "137",
      "machine_status": "Online",
      "tags": {
        "Account": "***********",
        "AmiId": "ami-7c412f13",
        "ExternalIp": "**********",
        "Hostname": "*****************",
        "InstanceId": "*****************",
        "InternalIp": "172.31.9.170",
        "LwTokenShort": "********",
        "SubnetId": "subnet-5fc7dd15",
        "VmInstanceType": "t2.micro",
        "VmProvider": "AWS",
        "VpcId": "vpc-a12b7dc9",
        "Zone": "eu-central-1c",
        "arch": "amd64",
        "os": "linux"
      },
```

**Comment by angelconcepcion** [comment]
Hi Scott, 

I think we spoke about being able to filter on machine tags when running
```
lacework vulnerability host list-cves
```
That way I can target all the hosts that share a similar tag and get the active/fixable results for that group.

**Comment by scottford-lw** [comment]
@angelconcepcion as it stands today the `/api/v1/external/vulnerabilities/host` api which `lacework vulnerability host list-cves` utilizes does not return machine tags. The `/api/v1/external/vulnerabilities/host/cveId/` api does have machine tags. 

I can open an FR with the platform team to see if they can add machine tags to `/api/v1/external/vulnerabilities/host` to filter on. 

Do you want filtering on `lists-hosts` as well? We can support that.

**Comment by angelconcepcion** [comment]
Definitely add the filtering capabilities to `/api/v1/external/vulnerabilities/host` and adding to `lists-hosts` can't hurt either.

**Comment by dmurray-lacework** [comment]
Closing as filters relate to v1 api.
