### ISSUE TITLE
Fix HTML generation test on Windows

### ISSUE THREAD

**Issue by afiune** [lacework/go-sdk#264]
There are a couple of integration tests that are not working properly on Windows systems.

![Screen Shot 2020-12-14 at 1 34 46 PM](https://user-images.githubusercontent.com/5712253/102081894-36fc6500-3dce-11eb-9e8b-9e59b71d89a3.png)

**Job:** https://app.circleci.com/pipelines/github/lacework/go-sdk/789/workflows/f8507955-e91a-4cf1-a299-9a849d7b479a/jobs/2833/steps
```
=== RUN   TestContainerVulnerabilityCommandScanHumanReadablePollGenerateHtml/assert_that_HTML_file_was_generated
mkdir ~/project/circleci-artifacts: The system cannot find the path specified.
rename C:\Users\circleci\AppData\Local\Temp\lacework-toml520612657/lacework-lacework-cli-sha256:135ce623ff08dffdc42ef916aa198b95ee184fa6798d51ac43367bc9d338f35e.html ~/project/circleci-artifacts/lacework-lacework-cli-sha256:135ce623ff08dffdc42ef916aa198b95ee184fa6798d51ac43367bc9d338f35e.html: The system cannot find the path specified.
```

## Acceptance Criteria
The HTML generation test on Windows should pass and store the artifacts in CircleCI.

**Comment by dmurray-lacework** [comment]
Closing as CircleCI is no longer used by the team
