### ISSUE TITLE
Ability to manage compliance suppression from CLI

### ISSUE THREAD

**Issue by ekelson-bcove** [lacework/go-sdk#426]
Use case:  I want to add a suppression tag for N AWS compliance rules.  I see it's possible to do that through some looping in API v1 via the suppression endpoint.  Could that feature be added to the lacework cli.  For example

`lacework compliance aws suppression --rules LW_AWS_XX_1 LW_AWS_XX_12 [--accounts LIST] [--regions LIST ] [--resource_name LIST] -t "tag1:value1" -t "tag2:value2"` 

Where everything in `[]` is optional and it being missing implies a `*`

**Comment by afiune** [comment]
https://lacework.atlassian.net/browse/ALLY-589

**Comment by dmurray-lacework** [comment]
Closing as this relates to deprecated api v1
