### ISSUE TITLE
Add integration tests to the Lacework CLI

### ISSUE THREAD

**Issue by ghost** [lacework/go-sdk#50]
We need to add some integration tests to the Lacework CLI (`lacework`),
my idea is to create a very lightweight framework that spawns new processes
to run the CLI with some test criteria, the framework should be able to return
things like STDOUT, STDERR, and the exit code.

**JIRA: ALLY-61**

**Comment by afiune** [comment]
Closed long time ago, also with this https://github.com/lacework/go-sdk/pull/191
