### ISSUE TITLE
Container Assessments default end time might be slightly ahead of server time and will get rejected by LW API

### ISSUE THREAD

**Issue by jvogt** [lacework/go-sdk#503]
Seems like if $local_time is slightly ahead of $server_time then the request is rejected
```
$ lacework vulnerability container list-assessments
<snip usage>
ERROR unable to get assessments:
  [GET] https://<redacted>.lacework.net/api/v1/external/vulnerabilities/container/GetAssessmentsForDateRange?END_TIME=2021-08-03T19%3A45%3A28Z&START_TIME=2021-07-27T19%3A47%3A28Z
  [400] endTime cannot be after current time
```

Fixed by manually setting start/end times where end time is at least a minute in the past:
```
$ lacework vulnerability container list-assessments --end 2021-08-03T19:52:28Z --start 2021-07-27T19:47:28Z
<success>
```

**Comment by afiune** [comment]
JIRA: https://lacework.atlassian.net/browse/ALLY-601

**Comment by afiune** [comment]
Hey @jvogt, good call to look at our telemetry, I will reach out to you privately but, could you please share the
version of the Lacework CLI you are/were using?

I am closing this ticket but if you see that it happens again, please re-open it! Thank you for your feedback 🥇

**Comment by mw-lw** [comment]
A customer (Paymentus Group) has reported encountering this issue:
> "I have updated lw cli to "lacework v1.18.3 (sha:e2775cf390accb6e38a0b1acfcf61859e23997f0) (time:20230506121053)" and I still get this error."

```
ERROR unable to find assessment information of image sha256:IMAGE:
  [POST] https://paymentus.lacework.net/api/v2/Vulnerabilities/Containers/search
  [400] endTime cannot be after current time
```

Including two instance of occurrence including the debug output and the "date" command:
```
date: Thu Apr 27 15:21:42 EDT 2023
"{\"timeFilter\":{\"startTime\":\"2023-04-20T19:16:44.920803432Z\",\"endTime\":\"2023-04-27T19:16:44.920803432Z\"}
```

```
date: Tue May  9 10:55:10 EDT 2023
{\"timeFilter\":{\"startTime\":\"2023-05-02T14:55:10.66806541Z\",\"endTime\":\"2023-05-09T14:55:10.66806541Z\"}
```

**Comment by jon-stewart** [comment]
Hi @mw-lw, this could be due the clock drifting on the customers server/laptop.  Can you ask the customer to ensure that the time is correct, and if not to sync the clock.

I'll ask api-server team about removing the need for `endTime` in the API time filters.

**Comment by jon-stewart** [comment]
Another workaround is for the customer to supply an explicit `--end -5m` to the command, with a number of minutes that accounts for the clock drift.

**Comment by afiune** [comment]
Closed by https://github.com/lacework/go-sdk/pull/1289
