### ISSUE TITLE
bug: lacework agent list percentage counter infinitely increases. 

### ISSUE THREAD

**Issue by getsec** [lacework/go-sdk#818]
**Describe the bug**
When running `lacework agent list` the percentage counter continuously increases without returning any response

```sh
lacework agent list
/ Fetching list of agents [1000%]...

# few mins later
| Fetching list of agents [1127%]...
```

**Expected behavior**
I'd expect this counter to be relative to the total number of requests it needs to make, but it seems like that isn't the case.

**Please complete the following information):**
- Operating System
```sh
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	         21E258
```
 - Lacework CLI version
 ```sh
 lacework v0.35.1 (sha:03b51e125c6acc1ac3b7927bac71e9bff1702878) (time:20220610160628)
 ```

**Comment by afiune** [comment]
@getsec we apologize for the inconveniences, we are having issues with our backend service that handles pagination, we are actively working on a fix and we will notify you as soon as this gets resolved.

- https://lacework.atlassian.net/browse/RAIN-32963
- https://lacework.atlassian.net/browse/SEV-1310

**Comment by afiune** [comment]
@getsec we have fixed the problem in our last deployment, I have verified that there is no infinite loop myself, I am going to close this issue but if you experience something different, please feel free to reopen it.

Thank you for your patience!! 💯

**Comment by getsec** [comment]
@afiune Sorry for the late reply - After running again - it looks all good!
