### ISSUE TITLE
feat: lacework agent list - does not show agent status.

### ISSUE THREAD

**Issue by getsec** [lacework/go-sdk#852]
# Feature Request

**Describe the Feature Request**
Lacework agent list CLI feature should report if the agent is ACTIVE or INACTIVE (like in the agent monitor web console view)

**Is your feature request related to a problem? Please describe**
When trying to programmatically get a count of lacework agents, the count is much larger than the active count within the web console. 

**Describe Preferred Solution**
Running `lacework agent list --json` gives us this (example)
```json
{
    "awsInstanceId": "i-xxxxx",
    "awsZone": "us-east-1c",
    "createdTime": "2022-07-01T13:00:20.627Z",
    "domain": "(none)",
    "hostname": "example",
    "kernel": "Linux",
    "kernelRelease": "5.4.0-1047",
    "kernelVersion": "#53-Ubuntu SMP Tue Mar 29 18:02:39 UTC 2022",
    "mid": 218518,
    "os": "Ubuntu",
    "osVersion": "18.04",
    "tags": {
      "Account": "xxxxx",
      "AmiId": "ami-xxxxx",
      "ExternalIp": "127.0.0.1",
      "Hostname": "iexample",
      "InstanceId": "i-xxxxxxxxx",
      "InternalIp": "10.103.80.49",
      "LwTokenShort": "xxx",
      "Name": "example-name,
      "SubnetId": "subnet-xxx",
      "VmInstanceType": "r5n.4xlarge",
      "VmProvider": "AWS",
      "VpcId": "vpc-xxx",
      "Zone": "us-east-1c",
      "arch": "amd64",
      "os": "linux"
    }
  },
```

I'd hope to see a value here that has the status, or possibly last check in date
```jsonc
{
    "awsInstanceId": "i-xxxxx",
    "awsZone": "us-east-1c",
    "createdTime": "2022-07-01T13:00:20.627Z",
    "domain": "(none)",
    "hostname": "example",
    "kernel": "Linux",
    "kernelRelease": "5.4.0-1047",
    "status": "ACTIVE", // suggestion
    "lastCheckIn": "2022-07-05T13:00:20.627Z", // suggetion
    "kernelVersion": "#53-Ubuntu SMP Tue Mar 29 18:02:39 UTC 2022",
    "mid": 218518,
    "os": "Ubuntu",
    "osVersion": "18.04",
    "tags": {
      "Account": "xxxxx",
      "AmiId": "ami-xxxxx",
      "ExternalIp": "127.0.0.1",
      "Hostname": "iexample",
      "InstanceId": "i-xxxxxxxxx",
      "InternalIp": "10.103.80.49",
      "LwTokenShort": "xxx",
      "Name": "example-name,
      "SubnetId": "subnet-xxx",
      "VmInstanceType": "r5n.4xlarge",
      "VmProvider": "AWS",
      "VpcId": "vpc-xxx",
      "Zone": "us-east-1c",
      "arch": "amd64",
      "os": "linux"
    }
  },
```

**Comment by afiune** [comment]
@getsec Hi there 👋🏽 - Thank you for your feedback! We will add both fields, `status` and `lastUpdate`!

**Comment by getsec** [comment]
@afiune As always, thank you! Never had such experience before :)

**Comment by afiune** [comment]
![tenor-90572303](https://user-images.githubusercontent.com/5712253/177599139-a5d0ba8c-f352-4e6c-a640-33d240b2fa3c.gif)

**Comment by afiune** [comment]
JIRA: https://lacework.atlassian.net/browse/ALLY-1071

**Comment by afiune** [comment]
@getsec we just merged https://github.com/lacework/go-sdk/pull/866

We will be releasing a new version of the Lacework CLI (`v0.40.0`) that will have this feature!

![tenor-100811232](https://user-images.githubusercontent.com/5712253/182971283-470c3f44-9aed-4e0d-a485-8cc9bc2e3081.gif)
