### ISSUE TITLE
bug: api.NewClient account format is confusing

### ISSUE THREAD

**Issue by hal-y** [lacework/go-sdk#860]
**Describe the bug**
When I tried to use this, I used the account string straight from the json file i downloaded when creating my api token.
That account string is in the format of `company.lacework.net`, which led to me failing to create the client instance since the url it used was `https://company.lacework.net.lacework.net`.
With the code as it is, if someone wanted to use an EU tenant, they'd have to provide the account in an even more unexpected format `company.fr` for it to work.

**To Reproduce**
1. Get account string as it's specified in the downloaded api token's json file.
2. try to create a new client with account from above, and see it fail.

**Expected behavior**
[This line](https://github.com/lacework/go-sdk/blob/8bc93baa67e3f8f063afc9b4f05199801cd8c170/api/client.go#L83) should be changed to check if the account already ends with `lacework.net` and not add it if it's already present.

**Screenshots**
N/A

**Please complete the following information):**
 - OS: [e.g. macOS Big Sur 11.5.2 ]
 - Version v0.38.0

**Additional context**

**Comment by afiune** [comment]
@hal-y thank you so much for your feedback! We will get this fixed in our next release.
