### ISSUE TITLE
feat(cli): CLI version tags for Docker image 

### ISSUE THREAD

**Issue by heywoodlh** [lacework/go-sdk#874]
# Feature Request

The current [lacework/lacework-cli Docker image](https://hub.docker.com/r/lacework/lacework-cli) has tags related to the underlying operating system in the container -- which, in my opinion, does not provide much value to those consuming the CLI through containers.

It would be nice if one could pull/run the container tag based on the version of the Lacework CLI -- not the underlying container's operating system.

i.e. `docker run -it --rm lacework/lacework-cli:v0.39.0`

Note: My PR for the multi-arch Dockerfile [provides an example of using a Github Action to extract the version string from the container and then applies that as a tag](https://github.com/heywoodlh/actions/blob/4979f27591a0d578bd713519dff93d17a30ce8e8/.github/workflows/lacework-cli-buildx.yml#L37-L50).

**Comment by dmurray-lacework** [comment]
Hey @heywoodlh thank you so much for raising this. The team has taken a quick look and we decided we need to rework our image tagging and release process. We'll create a ticket internally to make these changes. We'll keep you posted as soon as we start progress.

**Comment by dmurray-lacework** [comment]
This work is now complete https://hub.docker.com/r/lacework/lacework-cli/tags
