### ISSUE TITLE
feat: add line length as a check in `make lint`

### ISSUE THREAD

**Issue by nschmeller** [lacework/go-sdk#941]
# Feature Request

**Describe the Feature Request**
We'd prefer to have line lengths that are reasonable (say 100chars). We should include this in `make lint`

**Describe Preferred Solution**
I think `golangci-lint` has this feature, using a tool called LLL

**Additional Context**
Inspired by this discussion: https://github.com/lacework/go-sdk/pull/934#discussion_r993776438

**Comment by afiune** [comment]
![tenor-185495839](https://user-images.githubusercontent.com/5712253/195444868-2d76732a-97bb-4258-8730-e69d6f7da3a9.gif)
